In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv('../data/results.csv')
data.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [3]:
egypt = data[(data['home_team'] == 'Egypt') | (data['away_team'] == 'Egypt')]

In [4]:
egypt.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
809,1924-05-27,Egypt,Lithuania,10.0,0.0,Friendly,Vincennes,France,True
819,1924-06-22,Austria,Egypt,3.0,1.0,Friendly,Vienna,Austria,False
824,1924-06-29,Sweden,Egypt,5.0,0.0,Friendly,Stockholm,Sweden,False
1144,1928-06-14,Netherlands,Egypt,1.0,2.0,Friendly,Rotterdam,Netherlands,False
1146,1928-06-28,Luxembourg,Egypt,1.0,1.0,Friendly,Esch-sur-Alzette,Luxembourg,False

In [5]:
egy_l20 = egypt[-20:]
egy_l20

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
41025,2019-06-30,Egypt,Uganda,2.0,0.0,African Cup of Nations,Cairo,Egypt,False
41045,2019-07-06,Egypt,South Africa,0.0,1.0,African Cup of Nations,Cairo,Egypt,False
41444,2019-10-14,Egypt,Botswana,1.0,0.0,Friendly,Cairo,Egypt,False
41508,2019-11-07,Egypt,Liberia,1.0,0.0,Friendly,Alexandria,Egypt,False
41530,2019-11-14,Egypt,Kenya,1.0,1.0,African Cup of Nations qualification,Alexandria,Egypt,False
41633,2019-11-18,Comoros,Egypt,0.0,0.0,African Cup of Nations qualification,Moroni,Comoros,False
42075,2021-03-25,Kenya,Egypt,1.0,1.0,African Cup of Nations qualification,Nairobi,Kenya,False
42147,2021-03-29,Egypt,Comoros,4.0,0.0,African Cup of Nations qualification,Cairo,Egypt,False
42572,2021-09-01,Egypt,Angola,1.0,0.0,FIFA World Cup qualification,Cairo,Egypt,False
42654,2021-09-05,Gabon,Egypt,1.0,1.0,FIFA World Cup qualification,Franceville,Gabon,False
42740,2021-09-30,Egypt,Liberia,2.0,0.0,Friendly,Alexandria,Egypt,False
42794,2021-10-08,Egypt,Libya,1.0,0.0,FIFA World Cup qualification,Alexandria,Egypt,False
42856,2021-10-11,Libya,Egypt,0.0,3.0,FIFA World Cup qualification,Benina,Libya,False
42942,2021-11-12,Angola,Egypt,2.0,2.0,FIFA World Cup qualification,Luanda,Angola,False
43022,2021-11-16,Egypt,Gabon,2.0,1.0,FIFA World Cup qualification,Alexandria,Egypt,False
43056,2021-12-01,Egypt,Lebanon,1.0,0.0,Arab Cup,Doha,Qatar,True
43065,2021-12-04,Sudan,Egypt,0.0,5.0,Arab Cup,Doha,Qatar,True
43072,2021-12-07,Algeria,Egypt,1.0,1.0,Arab Cup,Al Wakrah,Qatar,True
43078,2021-12-11,Egypt,Jordan,3.0,1.0,Arab Cup,Al Wakrah,Qatar,True
43081,2021-12-15,Tunisia,Egypt,NaN,NaN,Arab Cup,Doha,Qatar,True

In [7]:
egy_win = 0
egy_lose = 0
egy_draw = 0
for i,j,k,l in zip(egy_l20['home_team'], egy_l20['away_team'], egy_l20['home_score'], egy_l20['away_score']):
    if ((i == 'Egypt') and (k>l)) or ((j == 'Egypt') and (k<l)):
        egy_win +=1
    elif ((i == 'Egypt') and (k<l)) or ((j == 'Egypt') and (k>l)):
        egy_lose +=1
    else:
        egy_draw += 1
    
print(egy_win, egy_lose, egy_draw)

12 1 7

In [8]:
sudan = data[(data['home_team'] == 'Sudan') | (data['away_team'] == 'Sudan')]

In [9]:
sudan.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
42944,2021-11-12,Sudan,Morocco,0.0,3.0,FIFA World Cup qualification,Rabat,Morocco,True
42999,2021-11-15,Guinea-Bissau,Sudan,0.0,0.0,FIFA World Cup qualification,Marrakech,Morocco,True
43055,2021-12-01,Algeria,Sudan,4.0,0.0,Arab Cup,Al Rayyan,Qatar,True
43065,2021-12-04,Sudan,Egypt,0.0,5.0,Arab Cup,Doha,Qatar,True
43073,2021-12-07,Lebanon,Sudan,1.0,0.0,Arab Cup,Al Rayyan,Qatar,True

In [10]:
sud_l20 = sudan[-20:]
sud_l20

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
41518,2019-11-13,Sudan,São Tomé and Príncipe,4.0,0.0,African Cup of Nations qualification,Omdurman,Sudan,False
41609,2019-11-17,South Africa,Sudan,1.0,0.0,African Cup of Nations qualification,Johannesburg,South Africa,False
41811,2020-10-09,Tunisia,Sudan,3.0,0.0,Friendly,Radès,Tunisia,False
41851,2020-10-12,Togo,Sudan,1.0,1.0,Friendly,Tunis,Tunisia,True
41893,2020-11-06,Ethiopia,Sudan,2.0,2.0,Friendly,Addis Ababa,Ethiopia,False
42044,2021-03-24,São Tomé and Príncipe,Sudan,0.0,2.0,African Cup of Nations qualification,Sao Tomé,São Tomé and Príncipe,False
42134,2021-03-28,Sudan,South Africa,2.0,0.0,African Cup of Nations qualification,Omdurman,Sudan,False
42388,2021-06-13,Sudan,Zambia,0.0,1.0,Friendly,Omdurman,Sudan,False
42439,2021-06-19,Libya,Sudan,0.0,1.0,Arab Cup qualification,Doha,Qatar,True
42561,2021-08-22,Niger,Sudan,2.0,1.0,Friendly,Dubai,United Arab Emirates,True
42562,2021-08-26,Sudan,Niger,3.0,0.0,Friendly,Dubai,United Arab Emirates,True
42595,2021-09-02,Morocco,Sudan,2.0,0.0,FIFA World Cup qualification,Rabat,Morocco,False
42694,2021-09-07,Sudan,Guinea-Bissau,2.0,4.0,FIFA World Cup qualification,Omdurman,Sudan,False
42745,2021-10-06,Sudan,Guinea,1.0,1.0,FIFA World Cup qualification,Marrakech,Morocco,True
42813,2021-10-09,Guinea,Sudan,2.0,2.0,FIFA World Cup qualification,Agadir,Morocco,True
42944,2021-11-12,Sudan,Morocco,0.0,3.0,FIFA World Cup qualification,Rabat,Morocco,True
42999,2021-11-15,Guinea-Bissau,Sudan,0.0,0.0,FIFA World Cup qualification,Marrakech,Morocco,True
43055,2021-12-01,Algeria,Sudan,4.0,0.0,Arab Cup,Al Rayyan,Qatar,True
43065,2021-12-04,Sudan,Egypt,0.0,5.0,Arab Cup,Doha,Qatar,True
43073,2021-12-07,Lebanon,Sudan,1.0,0.0,Arab Cup,Al Rayyan,Qatar,True

In [11]:
sud_win = 0
sud_lose = 0
sud_draw = 0
for i,j,k,l in zip(sud_l20['home_team'], sud_l20['away_team'], sud_l20['home_score'], sud_l20['away_score']):
    if ((i == 'Sudan') and (k>l)) or ((j == 'Sudan') and (k<l)):
        sud_win +=1
    elif ((i == 'Sudan') and (k<l)) or ((j == 'Sudan') and (k>l)):
        sud_lose +=1
    else:
        sud_draw += 1
    
print(sud_win, sud_lose, sud_draw)

5 10 5

In [ ]:
labels = ['WIN', 'LOSE', 'DRAW']

egy = [egy_win, egy_lose, egy_draw]
sud = [sud_win, sud_lose, sud_draw]

width = 0.25

x = np.arange(0, 3)

fig, ax = plt.subplots(figsize=(10,10))

y = list(range(0, 16, 2))

rects1 = ax.bar(x - width/2, egy, width, label='Egypt', color='k')
rects2 = ax.bar(x + width/2, sud, width, label='Sudan', color='g')

ax.set_ylabel('Number of Outcomes',fontsize=30, color='r')
ax.set_xlabel("Outcomes", fontsize=30, color='r')
ax.set_title("The last 20 matches of Egypt and Sudan", fontsize=25, color='b')
ax.set_xticklabels(labels, fontsize=15, color='b')
ax.set_yticklabels(y, rotation=0, fontsize=25, color='b')

ax.set_xticks(x)
plt.legend(fontsize=15)
plt.grid(True)
#plt.show()
plt.savefig("images/guineaBissau_nigeria.png")